accounts/urls.py
from django.conf.urls import url

from .views import *


urlpatterns = [
    url(r'^register/', RegisterView.as_view(), name='register'),
    url(r'^login/', LoginView.as_view(), name='login'),
    url(r'^logout/', LogoutView.as_view(), name='logout'),
    url(r'^edit-profile/', EditProfileView.as_view(), name='edit-profile'),
    #url(r'^profile/', profile_view, name='profile')
    url(r'^profile/(?:(?P<username>\w+)/)?$', ProfileView.as_view(), name='profile')
]

#url(r'^(?P<product_id>\w+)/$', views.product, name='product'),

api/urls.py
from django.conf.urls import url


from .views import ProductAPIView, ProductRudView

urlpatterns = [
    url(r'^products-list/$', ProductAPIView.as_view(), name='products-list'),
    url(r'^products-rud/(?P<pk>\d+)/$', ProductRudView.as_view(), name='product-rud')
]   

emarket/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.contrib.staticfiles import *
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView, TemplateView
from rest_framework_jwt.views import obtain_jwt_token

from . import views
import api


urlpatterns = [
    url(r'^$', RedirectView.as_view(url='main/')),
    url(r'^accounts/', include("accounts.urls", namespace='accounts')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^api/auth/login/$', obtain_jwt_token, name='api-login'),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^contacts/', views.ContactsView.as_view(), name='contacts'),
    url(r'^delivery/', views.DeliveryView.as_view(), name='delivery'),
    url(r'^main/', views.MainView.as_view(), name='main'),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^success/', views.SuccessView.as_view(), name='success'),
    url(r'^filtered_products/', views.FilteredProductsView.as_view(), name='filtered_products'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

first_shop/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.contrib.staticfiles import *
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView, TemplateView
from rest_framework_jwt.views import obtain_jwt_token

from . import views
import api


urlpatterns = [
    url(r'^$', RedirectView.as_view(url='main/')),
    url(r'^accounts/', include("accounts.urls", namespace='accounts')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^api/auth/login/$', obtain_jwt_token, name='api-login'),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^contacts/', views.ContactsView.as_view(), name='contacts'),
    url(r'^delivery/', views.DeliveryView.as_view(), name='delivery'),
    url(r'^main/', views.MainView.as_view(), name='main'),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^success/', views.SuccessView.as_view(), name='success'),
    url(r'^filtered_products/', views.FilteredProductsView.as_view(), name='filtered_products'),
]



urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^(?P<slug>[\w-]+)/$', views.ProductDetailView.as_view(), name='product'),
]

products/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.db.models import Max, Min
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse

from rest_framework.reverse import reverse as api_reverse
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFit

from .utils import unique_slug_generator
from comments.models import Comment


class Product(models.Model):

    class Meta:
        verbose_name = "Product"
        verbose_name_plural = "Products"

    slug                    = models.SlugField(default=None, null=True)
    name                    = models.CharField(max_length=64, blank=True, null=True, default=None, verbose_name="Products")
    price                   = models.IntegerField(null=True, default=0, verbose_name="Price")
    discount                = models.IntegerField(null=True, default=0, verbose_name="Discount (percent)")
    short_description       = models.TextField(null=True, max_length=100, blank=True, default=None)
    diagonal                = models.DecimalField(null=True, max_digits=5, decimal_places=1, blank=True, default=None, verbose_name="Diagonal (inches)")
    built_in_memory         = models.IntegerField(null=True, blank=True, default=None, verbose_name="Built in memory (Gb)")
    ram                     = models.IntegerField(null=True, blank=True, default=None, verbose_name="Ram (Gb)")
    os                      = models.CharField(null=True, max_length=30, blank=True, default=None)
    screen_resolution       = models.CharField(null=True, max_length=10, blank=True, default=None)
    processor               = models.CharField(null=True, max_length=30, blank=True, default=None)
    main_camera             = models.IntegerField(null=True, blank=True, default=None, verbose_name="Main camera (Mpx)")
    other_specifications    = models.TextField(null=True, blank=True, default=None)

    is_active           = models.BooleanField(default=True)
    created             = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated             = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s, %s" % (self.price, self.name)

    def get_main_img_url(self):
        """
        Returns main image of Product
        """
        return ProductImage.objects.get(product=self, is_main=True).image.url

    def get_price_with_discount(self):
        """
        Product price with discount (if it has discount)
        """
        try:
            discount_price = self.price - (self.price / 100 * self.discount)
        except:
            discount_price = self.price
        return int(discount_price)

    def get_absolute_url(self):
        return reverse("products:product", kwargs={"slug": self.slug})

    def get_api_url(self, request=None):
        return api_reverse("api:product-rud", kwargs={'pk': self.pk}, request=request)

    @classmethod
    def get_distinct_values_from_field(cls, field):
        values = list(cls.objects.all().values_list(field).order_by(field).distinct())
        if (None,) in values:
            values.remove((None,))
        return values

    @property
    def comments(self):
        """
        Comments of product
        """
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type

    @classmethod
    def get_max_price(cls):
        return cls.objects.aggregate(max=Max('price'))['max']

    @classmethod
    def get_min_price(cls):
        return cls.objects.aggregate(min=Min('price'))['min']

    @classmethod
    def get_max_memory(cls):
        return cls.objects.aggregate(max=Max('built_in_memory'))['max']

    @classmethod
    def get_min_memory(cls):
        return cls.objects.aggregate(min=Min('built_in_memory'))['min']


def pre_save_product_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        # instance.slug = create_slug(instance)
        instance.slug = unique_slug_generator(instance)

pre_save.connect(pre_save_product_receiver, sender=Product)


class ProductImage(models.Model):
    image       = models.ImageField(upload_to='products_images/')
    product     = models.ForeignKey(Product, blank=True, null=True, default=None)
    is_active   = models.BooleanField(default=True)
    is_main     = models.BooleanField(default=False)
    created     = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated     = models.DateTimeField(auto_now_add=False, auto_now=True)

    if is_main:
        thumbnail = ImageSpecField(source='image',
                                    processors=[ResizeToFit(200, 100)],
                                    format='JPEG',
                                    options={'quality': 60})
    else:
        thumbnail = None


    def __str__(self):
        return "%s" % self.id

    class Meta:
        verbose_name = "Photo"
        verbose_name_plural = "Photos"

products/views.py
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponseRedirect
from django.shortcuts import reverse
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormMixin

from comments.forms import CommentForm
from comments.models import Comment
from .models import Product


class ProductDetailView(FormMixin, DetailView):

    template_name   = 'products/product_detail.html'
    form_class      = CommentForm
    model           = Product

    def get_initial(self):
        initial = super().get_initial()

        # Hidden fields of the form contain content type of a Product model
        # and object id of a particular product.
        initial['content_type'] = self.object.get_content_type
        initial['object_id'] = self.object.id
        return initial

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form, *args, **kwargs):
        if not self.request.user.is_authenticated():
            return HttpResponseRedirect(reverse('accounts:login'))

        c_type = form.cleaned_data.get("content_type").lower()
        content_type = ContentType.objects.get(model=c_type)
        object_id = form.cleaned_data.get('object_id')
        content = form.cleaned_data.get("content")
        try:
            parent_id = int(self.request.POST.get("parent_id"))
            parent_obj = Comment.objects.get(id=parent_id)
        except:
            parent_obj = None

        new_comment, created = Comment.objects.get_or_create(
            user=self.request.user,
            content_type=content_type,
            object_id=object_id,
            content=content,
            parent=parent_obj,
        )
        return super().form_valid(self, **kwargs)

    def get_success_url(self):
        return self.object.get_absolute_url()

templates/products/product.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block style %}
    <link rel="stylesheet" href="{% static 'static_dev/css/product.css' %}">
{% endblock %}

{% block title %}
    {{ product.name }}
{% endblock title %}

{% block content %}
    <br>
    <br>
    <div class="container product">
        <div class="row row-main">

            <!-- Carousel -->
            <div class="col-lg-6">
                <div id="carouselImages" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        {% for image in product.productimage_set.all %}
                            <li data-target="#carouselImages" data-slide-to="{{ forloop.counter }}"
                                {% if image.is_main %}
                                    class="active"
                                {% endif %}
                            >
                            </li>
                        {% endfor %}
                    </ol>
                  <div class="carousel-inner">
                      {% for image in product.productimage_set.all %}
                        <div class="item
                            {% if image.is_main %}
                              active
                            {% endif %}
                        ">
                          <img  class="d-block w-100" src="{{ image.image.url }}" alt="">
                        </div>
                      {% endfor %}
                  </div>
                  <a class="left carousel-control" href="#carouselImages" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="right carousel-control" href="#carouselImages" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>

                </div>
            </div>

            <!-- Product -->
            <div class="col-lg-6">
                <h1 class="text-center">
                    {{ product.name }}
                </h1>
                </br>
                </br>
                </br>
                <div>
                    {{ product.short_description }}
                </div>
                </br>
                </br>
                <div class="add-to-basket-form">
                    <div>
                        <h4>
                            <b>Price:</b> {{ product.price }} RUB
                        </h4>
                    </div>
                    <form method="post" id="form_buying_product" class="form-inline">
                        {% csrf_token %}
                        Number:
                        <input type="number" size="1" value="1" min="1" class="product-nmb-form">
                        <button type="submit" class="btn btn-success changing-button" id="submit-btn"
                            data-id="{{ product.id }}">
                            Add to basket
                        </button>
                    </form>
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-lg-8">
                <p class='lead'>Specifications</p>
                <br>
                <table class="table">
                    <tr>
                        <td>Diagonal: </td>
                        <td>{{ product.diagonal }}</td>
                    </tr>
                    <tr>
                        <td>Display resolution: </td>
                        <td>{{ product.screen_resolution }}</td>
                    </tr>
                    <tr>
                        <td>Built in memory (Gb): </td>
                        <td>{{ product.built_in_memory }}</td>
                    </tr>
                    <tr>
                        <td>RAM (Gb):</td>
                        <td>{{ product.ram }}</td>
                    </tr>
                    <tr>
                        <td>Processor:</td>
                        <td>{{ product.processor }}</td>
                    </tr>
                    <tr>
                        <td>Main camera (Mpx):</td>
                        <td>{{ product.main_camera }}</td>
                    </tr>
                    <tr>
                        <td>Other specifications: </td>
                        <td>{{ product.other_specifications }}</td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="row">
            <p class='lead'>Comments</p>
            {% if request.user.is_authenticated %}
                <form method="POST" action="."> {% csrf_token %}
                    {{ comment_form|crispy }}
                    <input type='submit' value='Post comment' class='btn btn-default'>
                </form>
            {% else %}
                <p>You must login to comment </p>
            {% endif %}
            <hr/>
            {% for comment in comments %}
                <blockquote>
                    <p>{{ comment.content }}</p>
                    <footer>
                        via {{ comment.user }} | {{ comment.timestamp|timesince }} ago |
                        <a class='comment-reply-btn' href='#'>Reply</a>
                    </footer>

                    <div class='comment-reply'>
                        {% if comment.children %}<br>{% endif %}
                        {% for child_comment in comment.children reversed %}
                            <blockquote>
                                <p>{{ child_comment.content }}</p>
                                <footer>via {{ child_comment.user }} | {{ child_comment.timestamp|timesince }} ago</footer>
                            </blockquote>
                        {% endfor %}
                    <div class="comment-reply-form">
                        <br>
                        {% if request.user.is_authenticated %}
                            <span class="h5">Reply to {{ comment.user }}:</span>
                            <form method="POST" action="."> {% csrf_token %}
                                {{ comment_form|crispy }}
                                <input type='hidden' name='parent_id' value='{{ comment.id }}'>
                                <input type='submit' value='Reply' class='btn btn-default'>
                            </form>
                        {% else %}
                            <p>You must login to comment </p>
                        {% endif %}
                    </div>
                    </div>
                </blockquote>
                <hr/>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/products/product_detail.html
{% extends 'emarket/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load avatar_tags %}

{% block style %}
    <link rel="stylesheet" href="{% static 'static_dev/css/product.css' %}">
{% endblock %}

{% block title %}
    {{ product.name }}
{% endblock title %}

{% block content %}
    <br>
    <br>
    <div class="container product">
        <div class="row row-main">

            <!-- Carousel -->
            <div class="col-lg-6">
                <div id="carouselImages" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        {% for image in product.productimage_set.all %}
                            <li data-target="#carouselImages" data-slide-to="{{ forloop.counter }}"
                                {% if image.is_main %}
                                    class="active"
                                {% endif %}
                            >
                            </li>
                        {% endfor %}
                    </ol>
                  <div class="carousel-inner">
                      {% for image in product.productimage_set.all %}
                        <div class="item
                            {% if image.is_main %}
                              active
                            {% endif %}
                        ">
                          <img  class="d-block w-100" src="{{ image.image.url }}" alt="">
                        </div>
                      {% endfor %}
                  </div>
                  <a class="left carousel-control" href="#carouselImages" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="right carousel-control" href="#carouselImages" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>

                </div>
            </div>

            <!-- Product -->
            <div class="col-lg-6">
                <h1 class="text-center">
                    {{ product.name }}
                </h1>
                </br>
                </br>
                <div align="center">
                    <p>
                        {{ product.short_description|linebreaks }}
                    </p>
                </div>
                </br>
                </br>
                <div class="add-to-basket-form">
                    <div>
                        <h4>
                            <b>Price:</b>
                            {% if not product.discount %}
                                {{ product.price }}
                            {% else %}
                                <s>{{ product.price }}</s>
                                <span class="discount-price">{{ product.get_price_with_discount }}</span>
                            {% endif %}
                            RUB
                        </h4>
                    </div>
                    <form method="post" id="form_buying_product" class="form-inline">
                        {% csrf_token %}
                        Qty:
                        <input type="number" size="1" value="1" min="1" class="product-nmb-form">
                        <button type="submit" class="btn btn-success changing-button" id="submit-btn"
                            data-id="{{ product.id }}">
                            Add to basket
                        </button>
                    </form>
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-lg-8">
                <p class='lead'><h3>Specifications</h3></p>
                <br>
                <table class="table">
                    <tr>
                        <td>Diagonal: </td>
                        <td>{{ product.diagonal }}</td>
                    </tr>
                    <tr>
                        <td>Display resolution: </td>
                        <td>{{ product.screen_resolution }}</td>
                    </tr>
                    <tr>
                        <td>Built in memory (Gb): </td>
                        <td>{{ product.built_in_memory }}</td>
                    </tr>
                    <tr>
                        <td>RAM (Gb):</td>
                        <td>{{ product.ram }}</td>
                    </tr>
                    <tr>
                        <td>Processor:</td>
                        <td>{{ product.processor }}</td>
                    </tr>
                    <tr>
                        <td>Main camera (Mpx):</td>
                        <td>{{ product.main_camera }}</td>
                    </tr>
                    <tr>
                        <td>Other specifications: </td>
                        <td>{{ product.other_specifications }}</td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="product-comments">
            <div class="row">
                <p class='lead'><h3>Comments</h3></p>
                {% if request.user.is_authenticated %}
                    <form method="POST" action="."> {% csrf_token %}
                        {{ form|crispy }}
                        <input type='submit' value='Post comment' class='btn btn-default'>
                    </form>
                {% else %}
                    <p>&nbsp; You must login to comment </p>
                {% endif %}
                <hr/>
                {% for comment in product.comments %}
                    <blockquote>
                        <div class="comment-body">
                            {% avatar comment.user 55 %}
                            <p>{{ comment.content }}</p>
                        </div>
                        <footer>
                            via <a href="{% url 'accounts:profile' comment.user.username %}">{{ comment.user }}</a> |
                            {{ comment.timestamp|timesince }} ago |
                            <a class='comment-reply-btn' href='#'>Reply</a>
                        </footer>

                        <div class='comment-reply'>
                            {% if comment.children %}<br>{% endif %}
                            {% for child_comment in comment.children reversed %}
                                <blockquote>
                                    <div class="comment-body">
                                        {% avatar child_comment.user 40 %}
                                        <p>{{ child_comment.content }}</p>
                                    </div>
                                    <footer>
                                        <a href="{% url 'accounts:profile' child_comment.user.username %}">
                                            {{ child_comment.user }}
                                        </a> |
                                        {{ child_comment.timestamp|timesince }} ago
                                    </footer>
                                </blockquote>
                            {% endfor %}
                            <div class="comment-reply-form">
                                <br>
                                {% if request.user.is_authenticated %}
                                    <span class="h5">Reply to {{ comment.user }}:</span>
                                    <form method="POST" action="."> {% csrf_token %}
                                        {{ form|crispy }}
                                        <input type='hidden' name='parent_id' value='{{ comment.id }}'>
                                        <input type='submit' value='Reply' class='btn btn-default'>
                                    </form>
                                {% else %}
                                    <p>You must login to comment </p>
                                {% endif %}
                            </div>
                        </div>
                    </blockquote>
                    <hr/>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}