accounts/urls.py
from django.conf.urls import url

from .views import *


urlpatterns = [
    url(r'^register/', RegisterView.as_view(), name='register'),
    url(r'^login/', LoginView.as_view(), name='login'),
    url(r'^logout/', LogoutView.as_view(), name='logout'),
    url(r'^edit-profile/', EditProfileView.as_view(), name='edit-profile'),
    #url(r'^profile/', profile_view, name='profile')
    url(r'^profile/(?:(?P<username>\w+)/)?$', ProfileView.as_view(), name='profile')
]

#url(r'^(?P<product_id>\w+)/$', views.product, name='product'),

api/urls.py
from django.conf.urls import url


from .views import ProductAPIView, ProductRudView

urlpatterns = [
    url(r'^products-list/$', ProductAPIView.as_view(), name='products-list'),
    url(r'^products-rud/(?P<pk>\d+)/$', ProductRudView.as_view(), name='product-rud')
]   

emarket/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.contrib.staticfiles import *
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView, TemplateView
from rest_framework_jwt.views import obtain_jwt_token

from . import views
import api


urlpatterns = [
    url(r'^$', RedirectView.as_view(url='main/')),
    url(r'^accounts/', include("accounts.urls", namespace='accounts')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^api/auth/login/$', obtain_jwt_token, name='api-login'),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^contacts/', views.ContactsView.as_view(), name='contacts'),
    url(r'^delivery/', views.DeliveryView.as_view(), name='delivery'),
    url(r'^main/', views.MainView.as_view(), name='main'),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^success/', views.SuccessView.as_view(), name='success'),
    url(r'^filtered_products/', views.FilteredProductsView.as_view(), name='filtered_products'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

first_shop/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.contrib.staticfiles import *
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView, TemplateView
from rest_framework_jwt.views import obtain_jwt_token

from . import views
import api


urlpatterns = [
    url(r'^$', RedirectView.as_view(url='main/')),
    url(r'^accounts/', include("accounts.urls", namespace='accounts')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^api/auth/login/$', obtain_jwt_token, name='api-login'),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^contacts/', views.ContactsView.as_view(), name='contacts'),
    url(r'^delivery/', views.DeliveryView.as_view(), name='delivery'),
    url(r'^main/', views.MainView.as_view(), name='main'),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^success/', views.SuccessView.as_view(), name='success'),
    url(r'^filtered_products/', views.FilteredProductsView.as_view(), name='filtered_products'),
]



urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # url(r'^update_basket_list/$', views.update_basket_list, name="basket_list"),
    url(r'^update_basket_list/$', views.UpdateBasketList.as_view(), name="basket_list"),
    url(r'^checkout/$', views.CheckoutView.as_view(), name="checkout"),
    url(r'^success/$', views.SuccessView.as_view(), name="success"),
    url(r'^change_product_quantity/$', views.changeProductInBasketQuantity, name="changeProductQuantity"),
]

emarket/forms.py
from django import forms
from products.models import Product


class ContactForm(forms.Form):

    subject = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'size': '40', 'class': 'form-control'}))
    sender = forms.EmailField(widget=forms.TextInput(attrs={'size': '40', 'class': 'form-control'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    copy = forms.BooleanField(required=False)


def get_field_choices(field):
    val = Product.get_distinct_values_from_field(field)
    return ((v[0], v[0]) for v in val)


class FilterForm(forms.Form):
    """
    Filter form from the home page.
    """
    fields_with_choices = [
        'os',
        'diagonal',
        'processor',
        'ram'
    ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Creating choices for every field
        for field in self.fields_with_choices:
            self.fields[field].choices = get_field_choices(field)

        # Fields in the filter are not required
        for field in self.fields.keys():
            self.fields[field].required = False

    os          = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple())
    diagonal    = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple())
    processor   = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple())
    ram         = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple())

    memory_min  = forms.IntegerField(
        initial=Product.get_min_memory,
        max_value=9999,
        min_value=0
    )
    memory_max = forms.IntegerField(
        initial=Product.get_max_memory,
        max_value=9999,
        min_value=0
    )
    min_price = forms.IntegerField(label='Min price: ' + str(Product.get_min_price()) + ' RUB',
                                   initial=Product.get_min_price,
                                   widget=forms.NumberInput(attrs={'type': 'range',
                                                                   'min': Product.get_min_price,
                                                                   'id': 'mprice',
                                                                   'max': Product.get_max_price,
                                                                   'oninput': 'printprice("mprice")'}))

    max_price = forms.IntegerField(label='Max price: ' + str(Product.get_max_price()) + ' RUB',
                                   initial=Product.get_max_price,
                                   widget=forms.NumberInput(attrs={'type': 'range',
                                                                   'min': Product.get_min_price,
                                                                   'id': 'maxprice',
                                                                   'max': Product.get_max_price,
                                                                   'oninput': 'printprice("maxprice")'}))

    search = forms.CharField(max_length=200, widget=forms.HiddenInput())

emarket/views.py
from django.conf import settings
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView, FormMixin
from django.views.generic.list import ListView
from django.urls import reverse

from products.models import Product
from .forms import ContactForm, FilterForm


class MainView(ListView, FormMixin):
    model = Product
    template_name = 'emarket/home.html'
    form_class = FilterForm


class FilteredProductsView(FormView):
    template_name   = 'emarket/products_on_main_page.html'
    form_class      = FilterForm
    queryset        = Product.objects.all()

    def form_valid(self, form):
        prs = self.queryset
        data = form.cleaned_data

        oses = data['os']
        if oses: prs = prs.filter(os__in=oses)

        diagonals = data['diagonal']
        if diagonals: prs = prs.filter(diagonal__in=diagonals)

        processors = data['processor']
        if processors: prs = prs.filter(processor__in=processors)

        rams = data['ram']
        if rams: prs = prs.filter(ram__in=rams)

        mmin = data['memory_min']
        if mmin: prs = prs.filter(built_in_memory__gte=mmin)

        mmax = data['memory_max']
        if mmax: prs = prs.filter(built_in_memory__lte=mmax)

        minprice = data['min_price']
        if minprice and minprice > 0: prs = prs.filter(price__gte=minprice)

        maxprice = data['max_price']
        if maxprice and maxprice > 0: prs = prs.filter(price__lte=maxprice)

        search = data['search']
        if search: prs = prs.filter(name__icontains=search)

        return super().render_to_response({'product_list': prs})


class DeliveryView(TemplateView):
    template_name = 'emarket/delivery.html'


class SuccessView(TemplateView):
    template_name = 'emarket/success.html'


class ContactsView(FormView):
    template_name = 'emarket/contacts.html'
    form_class = ContactForm

    def get_success_url(self):
        return reverse('success')

    def form_valid(self, form):
        subject = form.cleaned_data['subject']
        sender = form.cleaned_data['sender']
        message = form.cleaned_data['message']
        message = f'''
Message from: {sender} 

{message} 
'''
        subject = '[Django Contacts] ' + subject
        copy = form.cleaned_data['copy']
        recepients = [settings.ADMINS[0][1]]
        if copy: recepients.append(sender)
        try:
            send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, recepients)
        except BadHeaderError:
            return HttpResponse('Invalid header found')
        return super().form_valid(form)

templates/emarket/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
      <link rel="stylesheet" href="{% static 'static_dev/css/base.css' %}">
      <link rel="shortcut icon" type="image/png" href="{% static "static_dev/img/favicon.ico" %}">

      <title>{% block title %}Emarket{% endblock %}</title>
      {% block style %} {% endblock style %}
  </head>

  <body>
    <div class="wrapper">
        <div class="wrapper-content">
            {% include 'emarket/navbar.html' %}

            {% block content %}
            {% endblock %}

        </div>
    </div>
    {% include 'emarket/footer.html' %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="VjEeINv9OSwtWFLAtmc4JCtEJXXBub00gtSnszmspDLCtC0I4z4nqz7rEFbIZLLU" crossorigin="anonymous"></script>
    <script src="{% static 'static_dev/js/script.js' %}"></script>
    {% block script %} {% endblock script %}
  </body>
</html>

templates/emarket/basket_items_list.html
{% if products_in_basket %}
    {% for product_in_basket in products_in_basket %}

        <div class="product-in-basket row">
            <div class="product-in-basket-img col-xs-4">
                <img src="{{ product_in_basket.get_product_thumbnail_url }}">
            </div>
            <div class="product-in-basket-info col-xs-6">
                <div class="product-in-basket-name">
                    <strong>{{ product_in_basket.product.name }}</strong>
                </div>
                <div class="product-in-basket-nmb-price">
                    <form class="form-change-product" method="post">
                        {% csrf_token %}
                        <input value="{{ product_in_basket.nmb }}" type="number"
                               class="num-products-input" min="1"
                               data-id="{{ product_in_basket.product.id }}"
                        > x <strong>{{ product_in_basket.product.get_price_with_discount }} RUB </strong>
                    </form>




                </div>
            </div>
            <div class="product-in-basket-remove-btn col-xs-1">
                <button type="button" class="btn  delete-from-basket" data-id='{{ product_in_basket.product.id }}'>
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>

    {% endfor %}
{% else %}
    <div class="product-in-basket">
        <div class="empty-basket"><h3>Basket is empty</h3></div>
    </div>
{% endif %}

<input id="hidden_basket_data"
       type="hidden"
       data-total-nmb="{{ products_total_nmb }}"
       data-total-price="{{ products_total_price }}"
       data-products-ids="{{ products_in_basket_ids }}"
>

templates/emarket/contacts.html
{% extends 'emarket/base.html' %}
{% load static %}

{% block title %}
    Contacts
{% endblock title %}

{% block content %}

    <div class="container contacts">
        <div class="row">
            <div class="col-lg-6">
                <h3>Requisites</h3>
                <hr>
                <p>
                    - <br>
                    - <br>
                </p>

                <h3>Address</h3>
                <hr>
                <p>
                    - <br>
                    - <br>
                </p>

                <h3>Phone</h3>
                <hr>
                <p>
                    - <br>
                    - <br>
                </p>

                <h3>Timetable</h3>
                <hr>
                <p>
                    - <br>
                    - <br>
                </p>

                <h3>Email</h3>
                <hr>
                <p>
                    <a href="mailto:m.nikolaev1@gmail.com">m.nikolaev1@gmail.com</a>
                </p>
            </div>
            <div class="col-lg-6">
                <h3>Contact us</h3>
                <hr>
                <form action="{% url 'contacts' %}" method="post">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    <div>
                      <label for="id_subject">Title:</label>
                      {{ form.subject.errors }}
                	  {{ form.subject }}
                    </div>
                    &nbsp;
                    <div>
                      <label for="id_sender">Your E-mail:</label>
                      {{ form.sender.errors }}
                	  {{ form.sender }}
                    </div>
                    &nbsp;
                    <div>
                      <label for="id_message">Message:</label>
                      {{ form.message.errors }}
                	  {{ form.message }}
                    </div>
                    &nbsp;
                    <div>
                      {{ form.copy.errors }}
                      <label for="id_copy">{{ form.copy }} Copy yourself </label>
                    </div>
                    <br>
                    <input type="submit" class="btn btn-success" value="Send"/>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

templates/emarket/delivery.html
{% extends 'emarket/base.html' %}
{% load static %}

{% block title %}
    Payment and delivery
{% endblock title %}

{% block content %}

    <div class="container delivery">
        <div class="row">
            <div class="col-lg-6">

                <h2>Payment</h2>
                <br>
                <h3>Cash/e-money</h3>
                <hr>
                <ol>
                    - <br>
                    - <br>
                    - <br>
                    - <br>
                    content <br>
                    - <br>
                    - <br>
                    - <br>
                    - <br>
                </ol>

                <h3>Bank transaction</h3>
                <hr>
                <ol>
                    - <br>
                    - <br>
                    - <br>
                    - <br>
                    content <br>
                    - <br>
                    - <br>
                    - <br>
                    - <br>
                </ol>
                </ol>


            </div>

            <div class="col-lg-6">
                <h2>Delivery</h2>
                <br>
                <h3>Self-delivery</h3>
                <hr>
                <ul>
                    - <br>
                    - <br>
                    - <br>
                    - <br>
                    content <br>
                    - <br>
                    - <br>
                    - <br>
                    - <br>
                </ul>

                <h3>Delivery service</h3>
                <hr>
                <ul>
                    - <br>
                    - <br>
                    content <br>
                    - <br>
                    - <br>
                </ul>

                <h3>Alternatives</h3>
                <hr>
                <ul>
                    - <br>
                    - <br>
                    content <br>
                    - <br>
                    - <br>
                </ul>
            </div>
        </div>
    </div>



{% endblock %}

templates/emarket/filter_form.html
<form class="filter-form" method="POST" action="{% url 'main' %}">{% csrf_token %}

    {% for field in form.visible_fields %}
        <h4>{{ field.label_tag }}</h4>
        {{ field }}
        <hr>
    {% endfor %}

    <input type="reset" id="reset_btn" value="Reset">


    <script>
        function printprice(price_id) {
            var id = '#' + price_id;
            var price = $(id).val();
            var labelselector = 'label[for=' + price_id + ']';
            var labeltext = price_id.startsWith('max') ? 'Max price: ' : 'Min price: ';
            $(labelselector).text(labeltext + price + ' RUB');
        }
    </script>

</form>

templates/emarket/footer.html
<footer class="footer">
    <div class="container">
        <div class="col-lg-4">
            <a href="{% url 'contacts' %}"><h4>Contacts</h4></a>
        </div>
        <div class="col-lg-4">
            <a href="{% url 'delivery' %}"><h4>Payment and delivery</h4></a>
        </div>
        <div class="col-lg-4">
            <a href="{% url 'orders:checkout' %}"><h4>Checkout</h4></a>
        </div>
    </div>
    <hr>
    <div class="copyright">
        <span >(c) Mikhail Nikolaev, 2020</span>
    </div>
</footer>

templates/emarket/home.html
{% extends 'emarket/base.html' %}
{% load static %}



{% block content %}

    <div class="section-top">
        <div class="home-image">
            <img src="{% static 'static_dev/img/slider0.jpg' %}" class="img-responsive" style="width: 100%;">
            <span class="h1">EMARKET</span>
        </div>
    </div>

    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-sm-4 col-sm-offset-8">
                    <div class="search-div">
                        <form method="POST" class="filter-form">
                            {% csrf_token %}
                            <div class="input-group">
                                <input type="text" class="form-control" value="{{ request.POST.search }}"
                                       placeholder="Search for..." name="search"
                                >
                                <span class="input-group-btn">
                                    <button id="search_button" class="btn btn-secondary" >Go!</button>
                                </span>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-md-3 col-sm-10 col-md-offset-0 col-sm-offset-1 filter-div">
                    <h3>Filter</h3>
                    <hr>
                    {% include 'emarket/filter_form.html' %}
                </div>
                <div class="col-md-9 col-sm-12">
                    <div id="product_items">
                        {% include 'emarket/products_on_main_page.html' %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    
{#    {% endif %}#}
{% endblock %}

templates/emarket/navbar.html
{% load static %}

<!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">

        <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'main' %}">Emarket</a>
            <button id="menu-btn" class="btn navbar-btn">
                  <span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
            </button>
        </div>

        <div id="navbar" class="navbar-collapse">
          <ul class="nav navbar-nav">
            <li id="main"><a href="{% url 'main' %}">Main</a></li>
            <li id="delivery"><a href="{% url 'delivery' %}">Payment and delivery</a></li>
            <li id="contacts"><a href="{% url 'contacts' %}">Contacts</a></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">

                {% if request.user.is_authenticated %}
                    <li>
                        <a href="{% url 'accounts:profile' %}">{{ request.user }}</a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:logout' %}">
                            <img class="login-icons" src="{% static 'static_dev/open-iconic-master/svg/account-logout.svg' %}">
                            logout
                        </a>
                    </li>
                {% else %}
                    <li id="login">
                        <a href="{% url 'accounts:login' %}">
                            <img class="login-icons" src="{% static 'static_dev/open-iconic-master/svg/account-login.svg' %}">
                            login
                        </a>
                    </li>
                    <li id="register">
                        <a href="{% url 'accounts:register' %}">
                            <img class="login-icons" src="{% static 'static_dev/open-iconic-master/svg/person.svg' %}">
                            sign up
                        </a>
                    </li>
                {% endif %}


                <!-- navbar basket -->
                <li id="checkout">
                    <a id="basket-in-navbar" href="{% url 'orders:checkout' %}"><span id="basket-text">Basket</span>
                        <img class="basket-icon" src="{% static 'static_dev/open-iconic-master/svg/cart.svg' %}">
                        <span id="basket_total_nmb"></span>
                    </a>

                    <div class="container basket">
                        <div class="basket-products-list">

                            <!-- Script.js puts html here -->

                        </div>
                        <div class="total-price-and-button row">
                            <div class="total-price-col col-xs-6">
                                <div class="total-price-div">
                                    Total: <span class="total_price h4"></span> RUB
                                </div>
                            </div>
                            <div class="col-xs-6 btn-to-basket-form">
                                <form action="{% url 'orders:checkout' %}">
                                    <button class="btn btn-info" id="btn_to_basket"><span class="h5">Checkout</span></button>
                                </form>
                            </div>
                        </div>
                    </div>
                </li>

          </ul>

        </div><!--/.nav-collapse -->
      </div>

    </nav>

templates/emarket/products_on_main_page.html
{% load static %}

{% for product in product_list %}
    <div class="product-item-col col-md-4 col-xs-12">
        <div class="product-item">
            <div class="product-img" >
                <div class="center-core">
{#                    <div style="height: fit-content">#}
                        <img src="{{ product.get_main_img_url }}">
{#                    </div>#}
                </div>
                {%  if product.discount  %}
                    <div class="discount">
                        SALE {{ product.discount }}%
                    </div>
                {% endif %}
                <div class="product-item-name">
                    <a href="{{ product.get_absolute_url }}">
                        <h4>{{ product.name }}</h4>
                    </a>
                </div>
            </div>
            <div class="product-info">
                <div class="specs">
                    <div>
                        <div>
                            <img src="{% static 'static_dev/open-iconic-master/svg/cog.svg' %}"
                             class="icon" alt="icon name"
                            > {{ product.os }}
                        </div>
                        <div>
                            <img src="{% static 'static_dev/open-iconic-master/svg/hard-drive.svg' %}"
                             class="icon" alt="icon name"
                            > {{ product.built_in_memory }} Gb
                        </div>
                    </div>
                    <div>
                        <div>
                            <img src="{% static 'static_dev/open-iconic-master/svg/fullscreen-enter.svg' %}"
                             class="icon" alt="icon name"
                            > {{ product.diagonal }}"
                        </div>
                        <div>
                            <img src="{% static 'static_dev/open-iconic-master/svg/camera-slr.svg' %}"
                             class="icon" alt="icon name"
                            > {{ product.main_camera }} Mpx
                        </div>
                    </div>
                </div>

                <div class="price-and-btn-div">
                    <div class="price-div">
                        {% if not product.discount %}
                            <span class="h4">
                                {{ product.price }} RUB
                            </span>
                        {% else %}
                            <span class="h4">
                                <s>{{ product.price }}</s>
                            </span>  &nbsp
                            <span class="h4 discount-price">
                                {{ product.get_price_with_discount }}
                            </span> <span class="h4">&nbspRUB</span>
                        {% endif %}
                    </div>
                    <div class="add-to-cart-btn">
                        <button class="btn btn-success changing-button" data-id="{{ product.id }}">
                            Add to basket
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endfor %}

templates/emarket/success.html
{% extends 'emarket/base.html' %}
{% load static %}


{% block content %}

    <hr><hr><hr>
    <h2 class="text-center">Done! Wi will contact you.</h2>


{% endblock %}